package cz.vut.fit.domainradar.models;

/**
 * A class containing constants representing the collector result codes.
 *
 * @author Ondřej Ondryáš
 */
@SuppressWarnings("ALL")
public final class ResultCodes {
    /**
     * The operation was successful.
     */
    public static final int OK = 0;

    /**
     * Invalid input message format (deserialization error).
     */
    public static final int INVALID_MESSAGE = 1;

    /**
     * Invalid domain name.
     */
    public static final int INVALID_DOMAIN_NAME = 2;

    /**
     * Invalid IP address.
     */
    public static final int INVALID_ADDRESS = 3;

    /**
     * The IP address is valid but the collector cannot process it.
     */
    public static final int UNSUPPORTED_ADDRESS = 4;

    /**
     * A generic error caused inside the collecting system (e.g. invalid state).
     */
    public static final int INTERNAL_ERROR = 5;

    /**
     * Error fetching from remote source.
     */
    public static final int CANNOT_FETCH = 10;

    /**
     * Timeout while waiting for a response.
     */
    public static final int TIMEOUT = 11;

    /**
     * Object does not exist.
     */
    public static final int NOT_FOUND = 12;

    /**
     * We are rate limited at the remote source.
     */
    public static final int RATE_LIMITED = 13;

    /**
     * Invalid format of remote source's response.
     */
    public static final int INVALID_RESPONSE = 14;

    /**
     * Local rate limiter in the immediate mode prevented
     * the request.
     */
    public static final int LOCAL_RATE_LIMIT = 15;

    /**
     * Could not pass the local rate limiter in a configured
     * time.
     */
    public static final int LRL_TIMEOUT = 16;

    /**
     * Unexpected DNS error.
     */
    public static final int OTHER_DNS_ERROR = 20;

    /**
     * RDAP servers are not available for the entity.
     */
    public static final int NO_ENDPOINT = 30;

    /**
     * WHOIS was not performed (RDAP was successful).
     */
    public static final int WHOIS_NOT_PERFORMED = 35;

    /**
     * ICMP destination unreachable (generated by the remote host or its inbound gateway
     * to inform the client that the destination is unreachable for some reason).
     */
    public static final int ICMP_DEST_UNREACHABLE = 40;

    /**
     * ICMP time exceeded (a datagram was discarded due to the time to live field reaching zero).
     */
    public static final int ICMP_TIME_EXCEEDED = 41;
}