in_classifier_order = ['dns_has_dnskey', 'dns_A_count', 'dns_AAAA_count', 'dns_MX_count', 'dns_NS_count',
                       'dns_TXT_count', 'dns_SOA_count', 'dns_CNAME_count', 'dns_zone_level', 'dns_zone_digit_count',
                       'dns_zone_len', 'dns_zone_entropy', 'dns_resolved_record_types', 'dns_dnssec_score',
                       'dns_ttl_avg', 'dns_ttl_stdev', 'dns_ttl_low', 'dns_ttl_mid', 'dns_ttl_distinct_count',
                       'dns_soa_primary_ns_level', 'dns_soa_primary_ns_digit_count', 'dns_soa_primary_ns_len',
                       'dns_soa_primary_ns_entropy', 'dns_soa_email_level', 'dns_soa_email_digit_count',
                       'dns_soa_email_len', 'dns_soa_email_entropy', 'dns_soa_refresh', 'dns_soa_retry',
                       'dns_soa_expire', 'dns_soa_min_ttl', 'dns_domain_name_in_mx', 'dns_mx_avg_len',
                       'dns_mx_avg_entropy', 'dns_txt_avg_len', 'dns_txt_avg_entropy',
                       'dns_txt_external_verification_score', 'dns_txt_spf_exists', 'dns_txt_dkim_exists',
                       'dns_txt_dmarc_exists', 'ip_count', 'ip_mean_average_rtt', 'ip_v4_ratio',
                       'ip_a_aaaa_to_all_ratio', 'ip_entropy', 'ip_as_address_entropy', 'ip_asn_entropy',
                       'ip_distinct_as_count', 'tls_has_tls', 'tls_chain_len', 'tls_is_self_signed',
                       'tls_root_authority_hash', 'tls_leaf_authority_hash', 'tls_negotiated_version_id',
                       'tls_negotiated_cipher_id', 'tls_root_cert_validity_len', 'tls_leaf_cert_validity_len',
                       'tls_broken_chain', 'tls_expired_chain', 'tls_total_extension_count', 'tls_critical_extensions',
                       'tls_with_policies_crt_count', 'tls_percentage_crt_with_policies',
                       'tls_x509_anypolicy_crt_count', 'tls_iso_policy_crt_count', 'tls_joint_isoitu_policy_crt_count',
                       'tls_subject_count', 'tls_server_auth_crt_count', 'tls_client_auth_crt_count',
                       'tls_CA_certs_in_chain_ratio', 'tls_unique_SLD_count', 'tls_common_name_count', 'lex_name_len',
                       'lex_has_digit', 'lex_phishing_keyword_count', 'lex_benign_keyword_count',
                       'lex_consecutive_chars', 'lex_tld_len', 'lex_tld_abuse_score', 'lex_tld_hash', 'lex_sld_len',
                       'lex_sld_norm_entropy', 'lex_sld_digit_count', 'lex_sld_digit_ratio',
                       'lex_sld_phishing_keyword_count', 'lex_sld_vowel_count', 'lex_sld_vowel_ratio',
                       'lex_sld_consonant_count', 'lex_sld_consonant_ratio', 'lex_sld_non_alphanum_count',
                       'lex_sld_non_alphanum_ratio', 'lex_sld_hex_count', 'lex_sld_hex_ratio', 'lex_sub_count',
                       'lex_stld_unique_char_count', 'lex_begins_with_digit', 'lex_www_flag',
                       'lex_sub_max_consonant_len', 'lex_sub_norm_entropy', 'lex_sub_digit_count',
                       'lex_sub_digit_ratio', 'lex_sub_vowel_count', 'lex_sub_vowel_ratio', 'lex_sub_consonant_count',
                       'lex_sub_consonant_ratio', 'lex_sub_non_alphanum_count', 'lex_sub_non_alphanum_ratio',
                       'lex_sub_hex_count', 'lex_sub_hex_ratio', 'lex_phishing_bigram_matches',
                       'lex_phishing_trigram_matches', 'lex_phishing_tetragram_matches',
                       'lex_phishing_pentagram_matches', 'lex_malware_bigram_matches', 'lex_malware_trigram_matches',
                       'lex_malware_tetragram_matches', 'lex_dga_bigram_matches', 'lex_dga_trigram_matches',
                       'lex_dga_tetragram_matches', 'lex_avg_part_len', 'lex_stdev_part_lens', 'lex_longest_part_len',
                       'lex_short_part_count', 'lex_medium_part_count', 'lex_long_part_count',
                       'lex_superlong_part_count', 'lex_shortest_sub_len', 'lex_ipv4_in_domain',
                       'lex_has_trusted_suffix', 'lex_has_wellknown_suffix', 'lex_has_cdn_suffix', 'lex_has_vps_suffix',
                       'lex_has_img_suffix', 'lex_suffix_score', 'geo_countries_count', 'geo_continents_count',
                       'geo_malic_host_country', 'geo_lat_stdev', 'geo_lon_stdev', 'geo_mean_lat', 'geo_mean_lon',
                       'geo_min_lat', 'geo_max_lat', 'geo_min_lon', 'geo_max_lon', 'geo_lat_range', 'geo_lon_range',
                       'geo_centroid_lat', 'geo_centroid_lon', 'geo_estimated_area', 'geo_continent_hash',
                       'geo_countries_hash', 'rdap_registration_period', 'rdap_domain_age',
                       'rdap_time_from_last_change', 'rdap_domain_active_time', 'rdap_has_dnssec',
                       'rdap_registrar_name_len', 'rdap_registrar_name_entropy', 'rdap_registrar_name_hash',
                       'rdap_registrant_name_len', 'rdap_registrant_name_entropy', 'rdap_admin_name_len',
                       'rdap_admin_name_entropy', 'rdap_admin_email_len', 'rdap_admin_email_entropy',
                       'rdap_ip_v4_count', 'rdap_ip_v6_count', 'rdap_ip_shortest_v4_prefix_len',
                       'rdap_ip_longest_v4_prefix_len', 'rdap_ip_shortest_v6_prefix_len',
                       'rdap_ip_longest_v6_prefix_len', 'rdap_ip_avg_admin_name_len', 'rdap_ip_avg_admin_name_entropy',
                       'rdap_ip_avg_admin_email_len', 'rdap_ip_avg_admin_email_entropy']
